project:
  type: manuscript
  output-dir: docs

repo-url: https://github.com/nfdi4objects/crm-rdf-ap

manuscript:
  article: index.qmd
  code-links:
    - repo
    - text: GitHub Issues
      href: https://github.com/nfdi4objects/crm-rdf-ap/issues

toc: true
bibliography: references.bib

format:
  html:
    theme: cosmo
    link-external-icon: false
    number-sections: true
    include-before-body:
      text: |
        <script src="./js/codemirror.js"></script>
        <script src="./js/sparql.js"></script>
        <script src="./js/turtle.js"></script>
        <script src="./js/runmode.js"></script>
        <script src="./js/highlight.js"></script>
    css:
      - codemirror.css
      - style.css
